# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anwers.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_answer_Dialog(object):
    def setupUi_ans(self, answer_Dialog,quest_no,ans_no):
        answer_Dialog.setObjectName("answer_Dialog")
        answer_Dialog.resize(1300, 800)
        self.scrollArea = QtWidgets.QScrollArea(answer_Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1280, 781))
        self.scrollArea.setMinimumSize(QtCore.QSize(1280, 680))
        self.scrollArea.setStyleSheet("background : transparent;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 2218, 2238))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setMinimumSize(QtCore.QSize(2200, 1000))
        self.frame.setStyleSheet("background : transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.answer_l = QtWidgets.QLabel(self.frame)
        self.answer_l.setGeometry(QtCore.QRect(0, 150, 2200, 772))
        self.answer_l.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"background : transparent;\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px")
        self.answer_l.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.answer_l.setObjectName("answer_l")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 2200, 121))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"background : transparent;\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.bg = QtWidgets.QLabel(answer_Dialog)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("pictures/try2-dark-stripes-background-elegant-design-wallpapers_518299-1505.jpg"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.bg.raise_()
        self.scrollArea.raise_()

        self.retranslateUi(answer_Dialog,quest_no,ans_no)
        QtCore.QMetaObject.connectSlotsByName(answer_Dialog)

    def retranslateUi(self, answer_Dialog,quest_no,ans_no):
        _translate = QtCore.QCoreApplication.translate
        answer_Dialog.setWindowTitle(_translate("answer_Dialog", "DARN IT-answers"))
        if ans_no == 1:
            self.answer_l.setText(_translate("answer_Dialog", "1)Topology related\n"
                                                                "Compare Bus and Star topology:\n"
                                                                "1)    Definition: The answer should begin by defining bus and star topology.\n"
                                                                "2)    Network Structure: The answer should compare the network structure of both topologies. \n"
                                                                "3)    Scalability: The answer should explain the scalability of both topologies. \n"
                                                                "4)    Fault Tolerance: The answer should discuss the fault tolerance of both topologies.\n"
                                                                "5)    Cost: The answer should compare the cost of implementing both topologies. \n"
                                                                "\n"
                                                                "\n"
                                                                "Compare Ring and Star Topology:\n"
                                                                "1)    Definition: The answer should begin by defining ring and star topology.\n"
                                                                "2)    Network Structure: The answer should compare the network structure of both topologies.\n"
                                                                "3)    Scalability: The answer should explain the scalability of both topologies.\n"
                                                                "4)    Fault Tolerance: The answer should discuss the fault tolerance of both topologies.\n"
                                                                "5)    Cost: The answer should compare the cost of implementing both topologies.\n"
                                                                "\n"
                                                                "Is there any relation between transmission media and topology:\n"
                                                                "1)    Definition: The answer should begin by defining transmission media and topology.\n"
                                                                "2)    Connection: The answer should discuss the connection between transmission media and topology.\n"
                                                                "3)    Distance: The answer should also discuss the distance limitations of different transmission media and their impact on topology.\n"
                                                                "4)    Performance: The answer should explain how the choice of transmission media and topology can impact the performance of the network.\n"
                                                                "5)    Flexibility: Finally, the answer should discuss the flexibility of transmission media and topology in meeting the changing needs of the network.\n"
                                                                ))
        if ans_no == 2 :
            self.answer_l.setText(_translate("answer_Dialog","Draw and explain the OSI Reference Model:\n"
                                                                "1)	Definition of the OSI Reference Model and its importance in the field of networking.\n"
                                                                "2)	Draw a detailed diagram of the OSI Reference model with correct order of the layers involved.\n"
                                                                "3)	Brief overview of the seven layers of the OSI Reference Model, highlighting their functions.\n"
                                                                "4)	Detailed explanation of the each layer, their roles in transmitting data between devices, and examples of their implementation.\n"
                                                                "5)	The advantages of the OSI Reference Model, such as the standardization of network communication, the ability to troubleshoot and diagnose network issues, and the compatibility of devices from different manufacturers.\n"
                                                                "6)	Limitations of the OSI Reference Model, such as its complexity and the difficulty of implementing it in real-world networks.\n"
                                                                "7)	Conclusion, summarizing the importance of the OSI Reference Model in networking and emphasizing the need for network administrators to understand it for effective communication and troubleshooting.\n"
                                                                ))

        if ans_no==3:
            self.answer_l.setText(_translate("answer_Dialog",'''Explain Token bucket algorithm:
1)	Introduction to congestion and its causes, including the impact of congestion on network performance.
2)	Explanation of the Token Bucket algorithm, which is a popular method for controlling network traffic and avoiding congestion.
3)	Discussion of how the Token Bucket algorithm works to regulate traffic and prevent congestion.
4)	Explanation of the advantages and disadvantages of using the Token Bucket algorithm for congestion control.
5)	Conclusion, summarizing the key points about congestion and the Token Bucket algorithm, and emphasizing the importance of effective congestion control mechanisms in network design.

How congestion is controlled in TCP:

1)	Explanation of the role of TCP congestion control mechanisms in preventing network congestion and improving network performance.
2)	Discussion of the main TCP congestion control mechanisms, including slow start, congestion avoidance, and fast retransmit/fast recovery.
3)	Explanation of how TCP slow start works to gradually increase the amount of data sent by a TCP connection until the network capacity is reached.
4)	Discussion of how TCP congestion avoidance works to prevent network congestion by dynamically adjusting the sending rate based on the network congestion level.
5)	Conclusion, summarizing the key points about TCP congestion control mechanisms and highlighting their importance in ensuring efficient and reliable data transmission in networks.'''))
        if ans_no==4:
            self.answer_l.setText(_translate("answer_Dialog", '''Header format:
1)	Brief introduction to IPv4 protocol and the importance of its header in network communication.
2)	Overview of the structure of an IPv4 packet header.
3)	Explanation of the Version, Header Length, Total Length, Time to Live, Protocol, Source IP Address, Destination IP Address, and Header Checksum fields and their respective roles in the header.
4)	Conclusion, summarizing the function and significance of each field in the IPv4 header.
'''))
        
        if ans_no==5:
            self.answer_l.setText(_translate("answer_Dialog", '''1)	Definition of wired and wireless media and their importance in network communication.

2)	Comparison of the physical characteristics of wired and wireless media, including the use of cables or airwaves to transmit data.

3)	Discussion of the advantages of wired media, such as higher bandwidth, reliability, and security due to the physical connection.

4)	Discussion of the advantages of wireless media, such as mobility, flexibility, and ease of installation.

5)	Comparison of the limitations of wired and wireless media, including potential cable damage or interference for wired media, and signal loss, interference, or security concerns for wireless media.

6)	Conclusion, summarizing the differences and similarities between wired and wireless media, and emphasizing the importance of choosing the appropriate medium based on the specific network requirements and constraints.
'''))
        if ans_no==6:
            self.answer_l.setText(_translate("answer_Dialog", '''1)	Introduction to ALOHA and Slotted ALOHA as two early methods for sharing a single communication channel among multiple users.
2)	Explanation of how ALOHA works by allowing users to transmit data at any time, but also risking data collisions if multiple users transmit at the same time.
3)	Discussion of the advantages and disadvantages of ALOHA, including its simplicity but also its high collision rate.
4)	Explanation of how Slotted ALOHA improves upon ALOHA by dividing time into discrete slots and allowing users to transmit data only at the beginning of each slot.
5)	Discussion of the advantages and disadvantages of Slotted ALOHA, including its reduced collision rate but also its potential for idle slots if no user has data to transmit.
6)	Conclusion, summarizing the key points about ALOHA and Slotted ALOHA and highlighting their historical significance as early methods for shared communication channel access.

Examine different types of ALOHA:
1)	Introduction to ALOHA as a method for shared communication channel access among multiple users.
2)	Explanation of pure ALOHA as the original version of ALOHA, in which users can transmit data at any time and risk data collisions if multiple users transmit at the same time.
3)	Discussion of slotted ALOHA as an improved version of ALOHA, in which time is divided into discrete slots and users can transmit data only at the beginning of each slot.
4)	Explanation of adaptive ALOHA as a further improvement over slotted ALOHA, in which the number of slots is dynamically adjusted based on the network load and the number of active users.
5)	Comparison of the different types of ALOHA, highlighting the advantages and disadvantages of each approach in terms of collision rate, throughput, and complexity.
6)	Conclusion, summarizing the key points about the different types of ALOHA and their relative strengths and weaknesses.

What is pure ALOHA and slotted ALOHA, what is efficiency, justify your answer.
1)	Explanation of pure ALOHA as a method for shared communication channel access among multiple users, in which users can transmit data at any time and risk data collisions if multiple users transmit at the same time.
2)	Description of slotted ALOHA as an improvement over pure ALOHA, in which time is divided into discrete slots and users can transmit data only at the beginning of each slot.
3)	Explanation of efficiency in the context of ALOHA, as the ratio of the number of successfully transmitted frames to the total number of frames transmitted.
4)	Justification of why slotted ALOHA is more efficient than pure ALOHA, by highlighting that the probability of collision in slotted ALOHA is reduced since users can only transmit at the beginning of each time slot, whereas in pure ALOHA users can transmit at any time and collisions are more likely to occur.
5)	Conclusion, summarizing the key points about pure ALOHA and slotted ALOHA, and highlighting the relative advantages and disadvantages of each approach in terms of efficiency and other factors.

Compare pure and slotted ALOHA:
1)	Definition of pure ALOHA and slotted ALOHA as two methods for shared communication channel access among multiple users.
2)	Explanation of how pure ALOHA allows users to transmit data at any time, while in slotted ALOHA, time is divided into discrete slots and users can only transmit data at the beginning of each slot.
3)	Comparison of the efficiency of pure ALOHA and slotted ALOHA, highlighting that pure ALOHA has lower efficiency due to a higher probability of data collisions, while slotted ALOHA has higher efficiency due to a lower probability of data collisions.
4)	Discussion of the advantages and disadvantages of pure ALOHA and slotted ALOHA. For example, pure ALOHA is simpler to implement and requires less coordination among users, but has lower efficiency and a higher probability of collisions. Slotted ALOHA, on the other hand, has higher efficiency and a lower probability of collisions, but requires more coordination and synchronization among users.
5)	Conclusion, summarizing the key differences between pure ALOHA and slotted ALOHA and highlighting the factors that could influence the choice of one method over the other in different network scenarios.
'''))
        if ans_no==7:
            self.answer_l.setText(_translate("answer_Dialog", '''1)	HDLC is a protocol used for communication between network equipment in a network.
2)	HDLC uses three different frame types: I, S, and U.
3)	I frames are for data transfer, S frames are for supervisory functions, and U frames are for unnumbered functions.
4)	Each frame type has a different format, with I frames having a fixed-length format that includes sequence numbers and data payloads, S frames having a variable-length format that includes sequence numbers and control functions, and U frames having a variable-length format that includes control functions and optional information.
5)	The different frame types are used for different purposes in network communication, and have their own advantages and disadvantages depending on the specific network scenario.
'''))
        if ans_no==8:
            self.answer_l.setText(_translate("answer_Dialog", '''1)	CSMA/CD is a media access control protocol used in Ethernet networks.
2)	It helps to avoid collisions when multiple nodes try to transmit data simultaneously on a shared medium.
3)	Before transmitting, a node listens for any ongoing transmission. If the medium is idle, it starts transmitting immediately.
4)	If multiple nodes transmit at the same time and a collision occurs, they stop transmission, wait for a random amount of time, and then retransmit.
5)	CSMA/CD is used in half-duplex Ethernet networks and has been replaced by CSMA/CA in wireless networks.
'''))
        if ans_no==9:
            self.answer_l.setText(_translate("answer_Dialog", '''1)	Definition and basic functionality of TCP and UDP.
2)	Differences in their communication model, such as connection-oriented vs. connectionless.
3)	Differences in their reliability and error-checking mechanisms.
4)	Applications and use cases for TCP and UDP, including common protocols and services that use each.
5)	Advantages and disadvantages of TCP and UDP, such as speed, resource utilization, and suitability for specific types of data transmission.
'''))
        if ans_no==10:
            self.answer_l.setText(_translate("answer_Dialog", '''sdad'''))
        if ans_no==11:
            self.answer_l.setText(_translate("answer_Dialog", '''sdad'''))
        if ans_no==12:
            self.answer_l.setText(_translate("answer_Dialog", '''sdad'''))
        if ans_no==13:
            self.answer_l.setText(_translate("answer_Dialog", '''sdad'''))
        if ans_no==15:
            self.answer_l.setText(_translate("answer_Dialog", '''sdad'''))



        if quest_no == 1:
            self.label_2.setText(_translate("answer_Dialog", "Q1-Compare Bus and Star topology ?\n"
    "     -Compare Ring and Star topology ?\n"
    "     -Is there any relationship between transmission media and topology ?"))
        if quest_no == 2:
            self.label_2.setText(_translate("answer_Dialog", "Q1-Draw  and explain the OSI Reference Model ?\n"
"     -What is the OSI Model? Give functions and services of each layer ?\n"
"     -What is OSI model , explain functions , services and protocols of each layer ?" ))
        if quest_no == 3:
            self.label_2.setText(_translate("answer_Dialog", "Q3-What is congestion and what are its causes? Explain Token bucket algorithm ?\n"
"     -How congestion is controlled in TCP ?"))
        if quest_no == 4:
            self.label_2.setText(_translate("answer_Dialog", "Q4-Header format of IPv4 ?"))
        if quest_no == 5:
            self.label_2.setText(_translate("answer_Dialog", "Q5-Compare wired and wireless media ?\n"
"     -Explain the different transmission media in networking ?\n"
"     -Explain guided transmission media in detail ?"))
        if quest_no == 6:
            self.label_2.setText(_translate("answer_Dialog", "Q6-Explain ALOHA and Slotted ALOHA ?\n"
"    -Examine different types of ALOHA ?\n"
"    -What is pure ALOHA and slotted ALOHA , what is efficiency , justify your answer ?\n"
"    -Compare pure and slotted ALOHA ?"))
        if quest_no == 7:
            self.label_2.setText(_translate("answer_Dialog", "Q7-What is HDLC , Compare frame formats,I frame , S frame , U frame ?\n"
"    -Explain HDLC protocol along with its frame structure ?   "))
        if quest_no == 8:
            self.label_2.setText(_translate("answer_Dialog", "Q8-Explain IP address and subnet mask ?\n"
"    -What is IP addressing?How it is classified?How is subnet addressing performed ?"))
        if quest_no == 9:
            self.label_2.setText(_translate("answer_Dialog", "Q9-Explain CSMA/CD ?\n"
"    -What is p persistant CSMA ?"))
        if quest_no == 10:
            self.label_2.setText(_translate("answer_Dialog", "Q10-Compare LAN,MAN,WAN ?\n"
"    -Examine advantages of LAN,MAN,WAN ?"))

if __name__ == "_main_":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    answer_Dialog = QtWidgets.QDialog()
    ui = Ui_answer_Dialog()
    ui.setupUi_ans(answer_Dialog)
    answer_Dialog.show()
    sys.exit(app.exec_())