# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anwers.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_answer_Dialog(object):
    def setupUi_ans(self, answer_Dialog,quest_no,ans_no):
        answer_Dialog.setObjectName("answer_Dialog")
        answer_Dialog.resize(1300, 800)
        self.scrollArea = QtWidgets.QScrollArea(answer_Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 1280, 781))
        self.scrollArea.setMinimumSize(QtCore.QSize(1280, 680))
        self.scrollArea.setStyleSheet("background : transparent;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 2218, 2238))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setMinimumSize(QtCore.QSize(2200, 1000))
        self.frame.setStyleSheet("background : transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.answer_l = QtWidgets.QLabel(self.frame)
        self.answer_l.setGeometry(QtCore.QRect(0, 150, 2200, 772))
        self.answer_l.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"background : transparent;\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px")
        self.answer_l.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.answer_l.setObjectName("answer_l")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 2200, 121))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"background : transparent;\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.bg = QtWidgets.QLabel(answer_Dialog)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("pictures/try2-dark-stripes-background-elegant-design-wallpapers_518299-1505.jpg"))
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.bg.raise_()
        self.scrollArea.raise_()

        self.retranslateUi(answer_Dialog,quest_no,ans_no)
        QtCore.QMetaObject.connectSlotsByName(answer_Dialog)

    def retranslateUi(self, answer_Dialog,quest_no,ans_no):
        _translate = QtCore.QCoreApplication.translate
        answer_Dialog.setWindowTitle(_translate("answer_Dialog", "DARN IT-answers"))
        if ans_no == 1:
            self.answer_l.setText(_translate("answer_Dialog", "1)Topology related\n"
                                                                "Compare Bus and Star topology:\n"
                                                                "1)    Definition: The answer should begin by defining bus and star topology.\n"
                                                                "2)    Network Structure: The answer should compare the network structure of both topologies. \n"
                                                                "3)    Scalability: The answer should explain the scalability of both topologies. \n"
                                                                "4)    Fault Tolerance: The answer should discuss the fault tolerance of both topologies.\n"
                                                                "5)    Cost: The answer should compare the cost of implementing both topologies. \n"
                                                                "\n"
                                                                "\n"
                                                                "Compare Ring and Star Topology:\n"
                                                                "1)    Definition: The answer should begin by defining ring and star topology.\n"
                                                                "2)    Network Structure: The answer should compare the network structure of both topologies.\n"
                                                                "3)    Scalability: The answer should explain the scalability of both topologies.\n"
                                                                "4)    Fault Tolerance: The answer should discuss the fault tolerance of both topologies.\n"
                                                                "5)    Cost: The answer should compare the cost of implementing both topologies.\n"
                                                                "\n"
                                                                "Is there any relation between transmission media and topology:\n"
                                                                "1)    Definition: The answer should begin by defining transmission media and topology.\n"
                                                                "2)    Connection: The answer should discuss the connection between transmission media and topology.\n"
                                                                "3)    Distance: The answer should also discuss the distance limitations of different transmission media and their impact on topology.\n"
                                                                "4)    Performance: The answer should explain how the choice of transmission media and topology can impact the performance of the network.\n"
                                                                "5)    Flexibility: Finally, the answer should discuss the flexibility of transmission media and topology in meeting the changing needs of the network.\n"
                                                                ))
        if ans_no == 2 :
            self.answer_l.setText(_translate("answer_Dialog","Draw and explain the OSI Reference Model:\n"
                                                                "1)	Definition of the OSI Reference Model and its importance in the field of networking.\n"
                                                                "2)	Draw a detailed diagram of the OSI Reference model with correct order of the layers involved.\n"
                                                                "3)	Brief overview of the seven layers of the OSI Reference Model, highlighting their functions.\n"
                                                                "4)	Detailed explanation of the each layer, their roles in transmitting data between devices, and examples of their implementation.\n"
                                                                "5)	The advantages of the OSI Reference Model, such as the standardization of network communication, the ability to troubleshoot and diagnose network issues, and the compatibility of devices from different manufacturers.\n"
                                                                "6)	Limitations of the OSI Reference Model, such as its complexity and the difficulty of implementing it in real-world networks.\n"
                                                                "7)	Conclusion, summarizing the importance of the OSI Reference Model in networking and emphasizing the need for network administrators to understand it for effective communication and troubleshooting.\n"
                                                                ))
        if quest_no == 1:
            self.label_2.setText(_translate("answer_Dialog", "Q1-Compare Bus and Star topology ?\n"
    "     -Compare Ring and Star topology ?\n"
    "     -Is there any relationship between transmission media and topology ?"))
        if quest_no == 2:
            self.label_2.setText(_translate("answer_Dialog", "Q1-Draw  and explain the OSI Reference Model ?\n"
"     -What is the OSI Model? Give functions and services of each layer ?\n"
"     -What is OSI model , explain functions , services and protocols of each layer ?" ))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    answer_Dialog = QtWidgets.QDialog()
    ui = Ui_answer_Dialog()
    ui.setupUi_ans(answer_Dialog)
    answer_Dialog.show()
    sys.exit(app.exec_())
