# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon

from cn_mod_1 import Ui_MainWindow_mod1
from cn_mod_2 import Ui_MainWindow_mod2
from cn_mod_3 import Ui_MainWindow_mod3
from cn_mod_4 import Ui_MainWindow_mod4
from cn_mod_5 import Ui_MainWindow_mod5
from cn_mod_6 import Ui_MainWindow_mod6


class Ui_MainWindow_cn(object):
    def open_mod_1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod1()
        self.ui.setupUi_mod1(self.window)
        self.window.show()
    def open_mod_2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod2()
        self.ui.setupUi_mod2(self.window)
        self.window.show()
    def open_mod_3(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod3()
        self.ui.setupUi_mod3(self.window)
        self.window.show()
    def open_mod_4(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod4()
        self.ui.setupUi_mod4(self.window)
        self.window.show()
    def open_mod_5(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod5()
        self.ui.setupUi_mod5(self.window)
        self.window.show()
    def open_mod_6(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod6()
        self.ui.setupUi_mod6(self.window)
        self.window.show()

    def go_back(self,MainWindow_cn):
        MainWindow_cn.hide()

    def setupUi_cn(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        MainWindow.setStyleSheet("")
        icon = QIcon()
        icon.addFile(u"pictures/icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(230, 31, 886, 61))
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.mod4 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_4())
        self.mod4.setGeometry(QtCore.QRect(46, 474, 821, 61))
        self.mod4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.mod4.setObjectName("mod4")
        self.mod1 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_1())
        self.mod1.setGeometry(QtCore.QRect(46, 174, 821, 61))
        self.mod1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.mod1.setObjectName("mod1")
        self.mod5 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_5())
        self.mod5.setGeometry(QtCore.QRect(46, 574, 821, 61))
        self.mod5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.mod5.setObjectName("mod5")
        self.mod6 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_6())
        self.mod6.setGeometry(QtCore.QRect(46, 674, 821, 61))
        self.mod6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.mod6.setObjectName("mod6")
        self.mod3 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_3())
        self.mod3.setGeometry(QtCore.QRect(46, 374, 821, 61))
        self.mod3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.mod3.setObjectName("mod3")
        self.mod2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_2())
        self.mod2.setGeometry(QtCore.QRect(46, 274, 821, 61))
        self.mod2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.mod2.setObjectName("mod2")
        self.pic = QtWidgets.QLabel(self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(890, 170, 371, 221))
        self.pic.setStyleSheet("")
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("../pictures/cn3.png"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.upload = QtWidgets.QPushButton(self.centralwidget)
        self.upload.setGeometry(QtCore.QRect(890, 450, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.upload.setFont(font)
        self.upload.setAutoFillBackground(False)
        self.upload.setStyleSheet("background-color:rgb(191, 255, 191);\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"                                  
"\n"
"\n"
"")
        self.upload.setObjectName("upload")
        self.back = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.go_back(MainWindow))
        self.back.setGeometry(QtCore.QRect(30, 30, 151, 61))
        self.back.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.back.setObjectName("back")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pictures/try2-dark-stripes-background-elegant-design-wallpapers_518299-1505.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.title.raise_()
        self.mod4.raise_()
        self.mod1.raise_()
        self.mod5.raise_()
        self.mod6.raise_()
        self.mod3.raise_()
        self.mod2.raise_()
        self.pic.raise_()
        self.upload.raise_()
        self.back.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DARN IT"))
        self.title.setText(_translate("MainWindow", "COMPUTER NETWORKS AND NETWORK DESIGN"))
        self.mod4.setText(_translate("MainWindow", "Module 4 :  Transport Layer and Session Layer"))
        self.mod1.setText(_translate("MainWindow", "Module 1 : Introduction to Computer Networks"))
        self.mod5.setText(_translate("MainWindow", "Module 5 : Presentation Layer and Application Layer"))
        self.mod6.setText(_translate("MainWindow", "Module 6 : Network Design Concepts"))
        self.mod3.setText(_translate("MainWindow", "Module 3 : Network Layer"))
        self.mod2.setText(_translate("MainWindow", "Module 2 : Physical Layer and Data Link Layer"))
        self.upload.setText(_translate("MainWindow", "UPLOAD"))
        self.back.setText(_translate("MainWindow", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_cn()
    ui.setupUi_cn(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
