# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cn_mod_1_f import Ui_MainWindow_mod
from faq import Ui_MainWindow_faq
from finalcode import ImageUploader
from statistic import Ui_MainWindow_stats
from custom import Ui_MainWindow_cust


class Ui_MainWindow_cn(object):
    def open_stats(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_stats()
        self.ui.setupUi_stats(self.window)
        self.window.show()
    def open_cust(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_cust()
        self.ui.setupUi_cust(self.window)
        self.window.show()

    def open_faq(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_faq()
        self.ui.setupUi_faq(self.window)
        self.window.show()
    def open_upload(self):
        self.window = ImageUploader()
        self.window.show()
    def open_mod_1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod()
        self.ui.setupUi_mod(self.window,1,0,0)
        self.window.show()
    def open_mod_2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod()
        self.ui.setupUi_mod(self.window,2,0,0)
        self.window.show()
    def open_mod_3(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod()
        self.ui.setupUi_mod(self.window,3,0,0)
        self.window.show()
    def open_mod_4(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod()
        self.ui.setupUi_mod(self.window,4,0,0)
        self.window.show()
    def open_mod_5(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod()
        self.ui.setupUi_mod(self.window,5,0,0)
        self.window.show()
    def open_mod_6(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod()
        self.ui.setupUi_mod(self.window,6,0,0)
        self.window.show()

    def open_all(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod()
        self.ui.setupUi_mod(self.window,7,0,0)
        self.window.show()

    def go_back(self,MainWindow_cn):
        MainWindow_cn.hide()

    def setupUi_cn(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\darsh\\Downloads\\DarnIT-main (1)\\DarnIT-main\\DARN IT\\pictures\\icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(230, 31, 886, 61))
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.mod4 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_4())
        self.mod4.setGeometry(QtCore.QRect(50, 390, 821, 61))
        self.mod4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.mod4.setObjectName("mod4")
        self.mod1 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_1())
        self.mod1.setGeometry(QtCore.QRect(50, 120, 821, 61))
        self.mod1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.mod1.setObjectName("mod1")
        self.mod5 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_5())
        self.mod5.setGeometry(QtCore.QRect(50, 490, 821, 61))
        self.mod5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.mod5.setObjectName("mod5")
        self.mod6 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_6())
        self.mod6.setGeometry(QtCore.QRect(50, 580, 821, 61))
        self.mod6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.mod6.setObjectName("mod6")
        self.mod3 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_3())
        self.mod3.setGeometry(QtCore.QRect(50, 300, 821, 61))
        self.mod3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.mod3.setObjectName("mod3")
        self.mod2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_mod_2())
        self.mod2.setGeometry(QtCore.QRect(50, 210, 821, 61))
        self.mod2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.mod2.setObjectName("mod2")
        self.pic = QtWidgets.QLabel(self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(890, 120, 381, 241))
        self.pic.setStyleSheet("")
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("C:\\Users\\darsh\\Downloads\\DarnIT-main (1)\\DarnIT-main\\DARN IT\\pictures\\cn3.png"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.upload = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_upload())
        self.upload.setGeometry(QtCore.QRect(890, 390, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.upload.setFont(font)
        self.upload.setAutoFillBackground(False)
        self.upload.setStyleSheet("background-color:#4CAF50;\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"\n"
"")
        self.upload.setObjectName("upload")
        self.back = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.go_back(MainWindow))
        self.back.setGeometry(QtCore.QRect(30, 30, 151, 61))
        self.back.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.back.setObjectName("back")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pictures/try2-dark-stripes-background-elegant-design-wallpapers_518299-1505.jpg"))
        self.label_2.setObjectName("label_2")
        self.mod3_2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_faq())
        self.mod3_2.setGeometry(QtCore.QRect(890, 490, 381, 61))
        self.mod3_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.mod3_2.setObjectName("mod3_3")
        self.mod3_3 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda :self.open_stats())
        self.mod3_3.setGeometry(QtCore.QRect(890, 580, 381, 61))
        self.mod3_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.mod3_3.setObjectName("mod3_3")
        self.mod6_2 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_all())
        self.mod6_2.setGeometry(QtCore.QRect(50, 670, 821, 61))
        self.mod6_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"")
        self.custom = QtWidgets.QPushButton(self.centralwidget,clicked = lambda : self.open_cust())
        self.custom.setObjectName(u"custom")
        self.custom.setGeometry(QtCore.QRect(890, 670, 381, 61))
        self.custom.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
                                  "color: rgb(255, 255, 255);\n"
                                  "font: 16pt \"Artifakt Element\";\n"
                                  "border : outset ;\n"
                                  "border-width : 1px;\n"
                                  "border-color: rgb(255, 255, 255);\n"
                                  "border-radius : 15px;\n"
                                  "\n"
                                  "")
        self.mod6_2.setObjectName("mod6_2")
        self.label_2.raise_()
        self.title.raise_()
        self.mod4.raise_()
        self.mod1.raise_()
        self.mod5.raise_()
        self.mod6.raise_()
        self.mod3.raise_()
        self.mod2.raise_()
        self.pic.raise_()
        self.upload.raise_()
        self.back.raise_()
        self.mod3_2.raise_()
        self.mod3_3.raise_()
        self.mod6_2.raise_()
        self.custom.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DARN IT "))
        self.title.setText(_translate("MainWindow", "COMPUTER NETWORKS AND NETWORK DESIGN"))
        self.mod4.setText(_translate("MainWindow", "Module 4 :  Transport Layer and Session Layer"))
        self.mod1.setText(_translate("MainWindow", "Module 1 : Introduction to Computer Networks"))
        self.mod5.setText(_translate("MainWindow", "Module 5 : Presentation Layer and Application Layer"))
        self.mod6.setText(_translate("MainWindow", "Module 6 : Network Design Concepts"))
        self.mod3.setText(_translate("MainWindow", "Module 3 : Network Layer"))
        self.mod2.setText(_translate("MainWindow", "Module 2 : Physical Layer and Data Link Layer"))
        self.upload.setText(_translate("MainWindow", "UPLOAD"))
        self.back.setText(_translate("MainWindow", "BACK"))
        self.mod3_2.setText(_translate("MainWindow", "FAQ"))
        self.mod3_3.setText(_translate("MainWindow", "Statistics"))
        self.mod6_2.setText(_translate("MainWindow", "ALL Questions"))
        self.custom.setText(_translate("MainWindow", "Custom"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_cn()
    ui.setupUi_cn(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
