# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cn_mod_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_mod2(object):
    def go_back(self,MainWindow):
        MainWindow.hide()
    def setupUi_mod2(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("pictures/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(300, 27, 658, 51))
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Artifakt Element\";\n"
"background : transparent;")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.back = QtWidgets.QPushButton(self.centralwidget,clicked=lambda :self.go_back(MainWindow))
        self.back.setGeometry(QtCore.QRect(20, 20, 151, 61))
        self.back.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);")
        self.back.setObjectName("back")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 110, 1280, 680))
        self.scrollArea.setMinimumSize(QtCore.QSize(1280, 680))
        self.scrollArea.setStyleSheet("background : transparent;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1257, 5018))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 5000))
        self.frame.setStyleSheet("background : transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1231, 42))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 50, 1231, 42))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(0, 100, 1231, 42))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 150, 1231, 42))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(0, 200, 1231, 42))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(0, 250, 1231, 42))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(0, 300, 1231, 42))
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 350, 1231, 42))
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(0, 400, 1231, 42))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(0, 450, 1231, 42))
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(0, 500, 1231, 42))
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(0, 560, 1231, 42))
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(0, 620, 1231, 42))
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(0, 670, 1231, 42))
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(0, 720, 1231, 42))
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(0, 770, 1231, 42))
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(0, 830, 1231, 42))
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 22pt \"Artifakt Element\";\n"
"background : transparent;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.yt = QtWidgets.QPushButton(self.centralwidget)
        self.yt.setGeometry(QtCore.QRect(1050, 20, 221, 61))
        self.yt.setStyleSheet("background-color:rgb(234, 51, 34);\n"
"color:rgb(255, 255, 255);\n"
"font: 14pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px")
        self.yt.setObjectName("yt")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("pictures/try2-dark-stripes-background-elegant-design-wallpapers_518299-1505.jpg"))
        self.label_19.setObjectName("label_19")
        self.label_19.raise_()
        self.title.raise_()
        self.back.raise_()
        self.scrollArea.raise_()
        self.yt.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DARN IT"))
        self.title.setText(_translate("MainWindow", "Module 2 : Physical Layer and Data Link Layer"))
        self.back.setText(_translate("MainWindow", "BACK"))
        self.label_2.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_3.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_4.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_5.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_6.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_7.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_8.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_9.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_10.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_11.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_12.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_13.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_14.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_15.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_16.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_17.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.label_18.setText(_translate("MainWindow", "MODULE 1 :INTRODUCTION"))
        self.yt.setText(_translate("MainWindow", "YouTube"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_mod2()
    ui.setupUi_mod2(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
