# # -*- coding: utf-8 -*-

# # Form implementation generated from reading ui file 'custom.ui'
# #
# # Created by: PyQt5 UI code generator 5.15.9
# #
# # WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.


# from PyQt5 import QtCore, QtGui, QtWidgets

# from cn_mod_1_f import Ui_MainWindow_mod

# class Ui_MainWindow_cust(object):
#     def temp_fn(self):
#         mod_no=self.mod_no_cb.currentText()
#         year = self.mod_no_cb.currentText()
#         marks = self.mod_no_cb.currentText()
#         self.open_mod(mod_no,year,marks)

#     def open_mod(self,mod_no,year,marks):
#         self.window = QtWidgets.QMainWindow()
#         self.ui = Ui_MainWindow_mod()
#         self.ui.setupUi_mod(self.window, mod_no, year, marks)

#         self.window.show()
#     def setupUi_cust(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(1300, 800)
#         font = QtGui.QFont()
#         font.setFamily("MS Sans Serif")
#         font.setPointSize(14)
#         font.setBold(False)
#         font.setWeight(50)
#         MainWindow.setFont(font)
#         icon = QtGui.QIcon()
#         icon.addPixmap(QtGui.QPixmap("C:\\Users\\darsh\\Downloads\\DarnIT-main (1)\\DarnIT-main\\DARN IT\\pictures\\icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         MainWindow.setWindowIcon(icon)
#         MainWindow.setWindowOpacity(1.0)
#         MainWindow.setAutoFillBackground(False)
#         MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#         self.f1 = QtWidgets.QFrame(self.centralwidget)
#         self.f1.setGeometry(QtCore.QRect(0, 0, 1300, 800))
#         self.f1.setStyleSheet("")
#         self.f1.setFrameShape(QtWidgets.QFrame.Box)
#         self.f1.setFrameShadow(QtWidgets.QFrame.Raised)
#         self.f1.setLineWidth(2)
#         self.f1.setObjectName("f1")
#         self.year_l = QtWidgets.QLabel(self.f1)
#         self.year_l.setGeometry(QtCore.QRect(150, 220, 81, 38))
#         font = QtGui.QFont()
#         font.setFamily("Artifakt Element")
#         font.setPointSize(20)
#         font.setBold(False)
#         font.setItalic(False)
#         font.setWeight(50)
#         self.year_l.setFont(font)
#         self.year_l.setStyleSheet("background : transparent;\n"
# "color: rgb(255, 255, 255);\n"
# "font: 20pt \"Artifakt Element\";")
#         self.year_l.setFrameShape(QtWidgets.QFrame.NoFrame)
#         self.year_l.setFrameShadow(QtWidgets.QFrame.Plain)
#         self.year_l.setObjectName("year_l")
#         self.logo = QtWidgets.QLabel(self.f1)
#         self.logo.setGeometry(QtCore.QRect(700, 70, 531, 481))
#         self.logo.setStyleSheet("background :  transparent;\n"
# "")
#         self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
#         self.logo.setFrameShadow(QtWidgets.QFrame.Plain)
#         self.logo.setLineWidth(0)
#         self.logo.setText("")
#         self.logo.setPixmap(QtGui.QPixmap("C:\\Users\\darsh\\Downloads\\DarnIT-main (1)\\DarnIT-main\\DARN IT\\pictures\\icon.png"))
#         self.logo.setScaledContents(True)
#         self.logo.setWordWrap(False)
#         self.logo.setObjectName("logo")
#         self.marks_l = QtWidgets.QLabel(self.f1)
#         self.marks_l.setGeometry(QtCore.QRect(150, 320, 121, 31))
#         font = QtGui.QFont()
#         font.setFamily("Artifakt Element")
#         font.setPointSize(20)
#         font.setBold(False)
#         font.setItalic(False)
#         font.setWeight(50)
#         self.marks_l.setFont(font)
#         self.marks_l.setStyleSheet("background : transparent;\n"
# "color: rgb(255, 255, 255);\n"
# "font: 20pt \"Artifakt Element\";")
#         self.marks_l.setFrameShape(QtWidgets.QFrame.NoFrame)
#         self.marks_l.setFrameShadow(QtWidgets.QFrame.Plain)
#         self.marks_l.setObjectName("marks_l")
#         self.darnit_l = QtWidgets.QLabel(self.f1)
#         self.darnit_l.setGeometry(QtCore.QRect(700, 590, 531, 151))
#         font = QtGui.QFont()
#         font.setFamily("Artifakt Element")
#         font.setPointSize(66)
#         font.setBold(False)
#         font.setItalic(False)
#         font.setUnderline(False)
#         font.setWeight(50)
#         self.darnit_l.setFont(font)
#         self.darnit_l.setStyleSheet("background : transparent;\n"
# "color: rgb(255, 255, 255);\n"
# "font: 66pt \"Artifakt Element\";")
#         self.darnit_l.setAlignment(QtCore.Qt.AlignCenter)
#         self.darnit_l.setObjectName("darnit_l")
#         self.year_cb = QtWidgets.QComboBox(self.f1)
#         self.year_cb.setGeometry(QtCore.QRect(390, 210, 181, 51))
#         self.year_cb.setAutoFillBackground(False)
#         self.year_cb.setStyleSheet("color: rgb(238, 244, 239);\n"
# "background-color: rgb(0, 85, 0);\n"
# "font: 18pt \"MS Shell Dlg 2\";\n"
# "background : transparent;\n"
# "opacity: 1.8;\n"
# "border : outset ;\n"
# "border-width : 1px;\n"
# "border-color: rgb(255, 255, 255);")
#         self.year_cb.setEditable(False)
#         self.year_cb.setDuplicatesEnabled(False)
#         self.year_cb.setFrame(True)
#         self.year_cb.setObjectName("year_cb")
#         self.year_cb.addItem("")
#         self.year_cb.addItem("")
#         self.year_cb.addItem("")
#         self.year_cb.addItem("")
#         self.year_cb.addItem("")
#         self.year_cb.addItem("")
#         self.year_cb.addItem("")
#         self.marks_cb = QtWidgets.QComboBox(self.f1)
#         self.marks_cb.setGeometry(QtCore.QRect(390, 310, 181, 51))
#         self.marks_cb.setAutoFillBackground(False)
#         self.marks_cb.setStyleSheet("color: rgb(238, 244, 239);\n"
# "background-color: rgb(0, 85, 0);\n"
# "font: 18pt \"MS Shell Dlg 2\";\n"
# "background : transparent;\n"
# "opacity: 1.8;\n"
# "border : outset ;\n"
# "border-width : 1px;\n"
# "border-color: rgb(255, 255, 255);")
#         self.marks_cb.setObjectName("marks_cb")
#         self.marks_cb.addItem("")
#         self.marks_cb.addItem("")
#         self.marks_cb.addItem("")
#         self.submit = QtWidgets.QPushButton(self.f1,clicked = lambda : self.temp_fn())
#         self.submit.setGeometry(QtCore.QRect(220, 550, 291, 51))
#         font = QtGui.QFont()
#         font.setFamily("Artifakt Element")
#         font.setPointSize(16)
#         font.setBold(False)
#         font.setItalic(False)
#         font.setWeight(50)
#         self.submit.setFont(font)
#         self.submit.setAutoFillBackground(False)
#         self.submit.setStyleSheet("background-color:#4CAF50;\n"
# "color: rgb(0, 0, 0);\n"
# "font: 16pt \"Artifakt Element\";\n"
# "border : outset ;\n"
# "border-width : 1px;\n"
# "border-color: rgb(255, 255, 255);\n"
# "border-radius : 15px;\n"
# "\n"
# "\n"
# "")
#         self.submit.setObjectName("submit")
#         self.bg = QtWidgets.QLabel(self.f1)
#         self.bg.setGeometry(QtCore.QRect(0, 0, 1300, 800))
#         self.bg.setText("")
#         self.bg.setPixmap(QtGui.QPixmap("C:\\Users\\darsh\\Downloads\\DarnIT-main (1)\\DarnIT-main\\DARN IT\\pictures\\try2-dark-stripes-background-elegant-design-wallpapers_518299-1505.jpg"))
#         self.bg.setObjectName("bg")
#         self.mod_no_cb = QtWidgets.QComboBox(self.f1)
#         self.mod_no_cb.setGeometry(QtCore.QRect(390, 410, 181, 51))
#         self.mod_no_cb.setAutoFillBackground(False)
#         self.mod_no_cb.setStyleSheet("color: rgb(238, 244, 239);\n"
# "background-color: rgb(0, 85, 0);\n"
# "font: 18pt \"MS Shell Dlg 2\";\n"
# "background : transparent;\n"
# "opacity: 1.8;\n"
# "border : outset ;\n"
# "border-width : 1px;\n"
# "border-color: rgb(255, 255, 255);")
#         self.mod_no_cb.setObjectName("mod_no_cb")
#         self.mod_no_cb.addItem("")
#         self.mod_no_cb.addItem("")
#         self.mod_no_cb.addItem("")
#         self.mod_no_cb.addItem("")
#         self.mod_no_cb.addItem("")
#         self.mod_no_cb.addItem("")
#         self.mod_no_cb.addItem("")
#         self.mod_no_l = QtWidgets.QLabel(self.f1)
#         self.mod_no_l.setGeometry(QtCore.QRect(150, 420, 171, 41))
#         font = QtGui.QFont()
#         font.setFamily("Artifakt Element")
#         font.setPointSize(20)
#         font.setBold(False)
#         font.setItalic(False)
#         font.setWeight(50)
#         self.mod_no_l.setFont(font)
#         self.mod_no_l.setStyleSheet("background : transparent;\n"
# "color: rgb(255, 255, 255);\n"
# "font: 20pt \"Artifakt Element\";")
#         self.mod_no_l.setFrameShape(QtWidgets.QFrame.NoFrame)
#         self.mod_no_l.setFrameShadow(QtWidgets.QFrame.Plain)
#         self.mod_no_l.setObjectName("mod_no_l")
#         self.bg.raise_()
#         self.year_l.raise_()
#         self.logo.raise_()
#         self.marks_l.raise_()
#         self.darnit_l.raise_()
#         self.year_cb.raise_()
#         self.marks_cb.raise_()
#         self.submit.raise_()
#         self.mod_no_cb.raise_()
#         self.mod_no_l.raise_()
#         MainWindow.setCentralWidget(self.centralwidget)

#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)

#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "DARN IT"))
#         self.year_l.setText(_translate("MainWindow", "Year :"))
#         self.marks_l.setText(_translate("MainWindow", "Marks :"))
#         self.darnit_l.setText(_translate("MainWindow", "DARN-IT"))
#         self.year_cb.setItemText(0, _translate("MainWindow", "2022"))
#         self.year_cb.setItemText(1, _translate("MainWindow", "2019"))
#         self.year_cb.setItemText(2, _translate("MainWindow", "2018"))
#         self.year_cb.setItemText(3, _translate("MainWindow", "2017"))
#         self.year_cb.setItemText(4, _translate("MainWindow", "2016"))
#         self.year_cb.setItemText(5, _translate("MainWindow", "2015"))
#         self.year_cb.setItemText(6, _translate("MainWindow", "2014"))
#         self.marks_cb.setItemText(0, _translate("MainWindow", "10 "))
#         self.marks_cb.setItemText(1, _translate("MainWindow", "05"))
#         self.marks_cb.setItemText(2, _translate("MainWindow", "03"))
#         self.submit.setText(_translate("MainWindow", "SUBMIT"))
#         self.mod_no_cb.setItemText(0, _translate("MainWindow", "01"))
#         self.mod_no_cb.setItemText(1, _translate("MainWindow", "02"))
#         self.mod_no_cb.setItemText(2, _translate("MainWindow", "03"))
#         self.mod_no_cb.setItemText(3, _translate("MainWindow", "04"))
#         self.mod_no_cb.setItemText(4, _translate("MainWindow", "05"))
#         self.mod_no_cb.setItemText(5, _translate("MainWindow", "06"))
#         self.mod_no_cb.setItemText(6, _translate("MainWindow", "All"))
#         self.mod_no_l.setText(_translate("MainWindow", "Module no :"))



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow_cust()
#     ui.setupUi_cust(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from cn_mod_1_f import Ui_MainWindow_mod

class Ui_MainWindow_cust(object):
    def temp_fn(self):
        mod_no=self.mod_no_cb.currentText()
        year = self.year_cb.currentText()
        marks = self.marks_cb.currentText()
        self.open_mod(mod_no,year,marks)

    def open_mod(self,mod_no,year,marks):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_mod()
        self.ui.setupUi_mod(self.window, mod_no, year, marks)

        self.window.show()
    def setupUi_cust(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 800)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\darsh\\Downloads\\DarnIT-main (1)\\DarnIT-main\\DARN IT\\pictures\\icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.f1 = QtWidgets.QFrame(self.centralwidget)
        self.f1.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        self.f1.setStyleSheet("")
        self.f1.setFrameShape(QtWidgets.QFrame.Box)
        self.f1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f1.setLineWidth(2)
        self.f1.setObjectName("f1")
        self.year_l = QtWidgets.QLabel(self.f1)
        self.year_l.setGeometry(QtCore.QRect(150, 220, 81, 38))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.year_l.setFont(font)
        self.year_l.setStyleSheet("background : transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Artifakt Element\";")
        self.year_l.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.year_l.setFrameShadow(QtWidgets.QFrame.Plain)
        self.year_l.setObjectName("year_l")
        self.logo = QtWidgets.QLabel(self.f1)
        self.logo.setGeometry(QtCore.QRect(700, 70, 531, 481))
        self.logo.setStyleSheet("background :  transparent;\n"
"")
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo.setLineWidth(0)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:\\Users\\darsh\\Downloads\\DarnIT-main (1)\\DarnIT-main\\DARN IT\\pictures\\icon.png"))
        self.logo.setScaledContents(True)
        self.logo.setWordWrap(False)
        self.logo.setObjectName("logo")
        self.marks_l = QtWidgets.QLabel(self.f1)
        self.marks_l.setGeometry(QtCore.QRect(150, 320, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.marks_l.setFont(font)
        self.marks_l.setStyleSheet("background : transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Artifakt Element\";")
        self.marks_l.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.marks_l.setFrameShadow(QtWidgets.QFrame.Plain)
        self.marks_l.setObjectName("marks_l")
        self.darnit_l = QtWidgets.QLabel(self.f1)
        self.darnit_l.setGeometry(QtCore.QRect(700, 590, 531, 151))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element")
        font.setPointSize(66)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.darnit_l.setFont(font)
        self.darnit_l.setStyleSheet("background : transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 66pt \"Artifakt Element\";")
        self.darnit_l.setAlignment(QtCore.Qt.AlignCenter)
        self.darnit_l.setObjectName("darnit_l")
        self.year_cb = QtWidgets.QComboBox(self.f1)
        self.year_cb.setGeometry(QtCore.QRect(390, 210, 181, 51))
        self.year_cb.setAutoFillBackground(False)
        self.year_cb.setStyleSheet("color: rgb(238, 244, 239);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"background : transparent;\n"
"opacity: 1.8;\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);")
        self.year_cb.setEditable(False)
        self.year_cb.setDuplicatesEnabled(False)
        self.year_cb.setFrame(True)
        self.year_cb.setObjectName("year_cb")
        self.year_cb.addItem("")
        self.year_cb.addItem("")
        self.year_cb.addItem("")
        self.year_cb.addItem("")
        self.year_cb.addItem("")
        self.year_cb.addItem("")
        self.year_cb.addItem("")
        self.marks_cb = QtWidgets.QComboBox(self.f1)
        self.marks_cb.setGeometry(QtCore.QRect(390, 310, 181, 51))
        self.marks_cb.setAutoFillBackground(False)
        self.marks_cb.setStyleSheet("color: rgb(238, 244, 239);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"background : transparent;\n"
"opacity: 1.8;\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);")
        self.marks_cb.setObjectName("marks_cb")
        self.marks_cb.addItem("")
        self.marks_cb.addItem("")
        self.marks_cb.addItem("")
        self.submit = QtWidgets.QPushButton(self.f1,clicked = lambda : self.temp_fn())
        self.submit.setGeometry(QtCore.QRect(220, 550, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.submit.setFont(font)
        self.submit.setAutoFillBackground(False)
        self.submit.setStyleSheet("background-color:#4CAF50;\n"
"color: rgb(0, 0, 0);\n"
"font: 16pt \"Artifakt Element\";\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius : 15px;\n"
"\n"
"\n"
"")
        self.submit.setObjectName("submit")
        self.bg = QtWidgets.QLabel(self.f1)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1300, 800))
        self.bg.setText("")
        self.bg.setPixmap(QtGui.QPixmap("C:\\Users\\darsh\\Downloads\\DarnIT-main (1)\\DarnIT-main\\DARN IT\\pictures\\try2-dark-stripes-background-elegant-design-wallpapers_518299-1505.jpg"))
        self.bg.setObjectName("bg")
        self.mod_no_cb = QtWidgets.QComboBox(self.f1)
        self.mod_no_cb.setGeometry(QtCore.QRect(390, 410, 181, 51))
        self.mod_no_cb.setAutoFillBackground(False)
        self.mod_no_cb.setStyleSheet("color: rgb(238, 244, 239);\n"
"background-color: rgb(0, 85, 0);\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"background : transparent;\n"
"opacity: 1.8;\n"
"border : outset ;\n"
"border-width : 1px;\n"
"border-color: rgb(255, 255, 255);")
        self.mod_no_cb.setObjectName("mod_no_cb")
        self.mod_no_cb.addItem("")
        self.mod_no_cb.addItem("")
        self.mod_no_cb.addItem("")
        self.mod_no_cb.addItem("")
        self.mod_no_cb.addItem("")
        self.mod_no_cb.addItem("")
        self.mod_no_cb.addItem("")
        self.mod_no_l = QtWidgets.QLabel(self.f1)
        self.mod_no_l.setGeometry(QtCore.QRect(150, 420, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mod_no_l.setFont(font)
        self.mod_no_l.setStyleSheet("background : transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Artifakt Element\";")
        self.mod_no_l.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mod_no_l.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mod_no_l.setObjectName("mod_no_l")
        self.bg.raise_()
        self.year_l.raise_()
        self.logo.raise_()
        self.marks_l.raise_()
        self.darnit_l.raise_()
        self.year_cb.raise_()
        self.marks_cb.raise_()
        self.submit.raise_()
        self.mod_no_cb.raise_()
        self.mod_no_l.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DARN IT"))
        self.year_l.setText(_translate("MainWindow", "Year :"))
        self.marks_l.setText(_translate("MainWindow", "Marks :"))
        self.darnit_l.setText(_translate("MainWindow", "DARN-IT"))
        self.year_cb.setItemText(0, _translate("MainWindow", "2022"))
        self.year_cb.setItemText(1, _translate("MainWindow", "2019"))
        self.year_cb.setItemText(2, _translate("MainWindow", "2018"))
        self.year_cb.setItemText(3, _translate("MainWindow", "2017"))
        self.year_cb.setItemText(4, _translate("MainWindow", "2016"))
        self.year_cb.setItemText(5, _translate("MainWindow", "2015"))
        self.year_cb.setItemText(6, _translate("MainWindow", "2014"))
        self.marks_cb.setItemText(0, _translate("MainWindow", "10 "))
        self.marks_cb.setItemText(1, _translate("MainWindow", "05"))
        self.marks_cb.setItemText(2, _translate("MainWindow", "03"))
        self.submit.setText(_translate("MainWindow", "SUBMIT"))
        self.mod_no_cb.setItemText(0, _translate("MainWindow", "01"))
        self.mod_no_cb.setItemText(1, _translate("MainWindow", "02"))
        self.mod_no_cb.setItemText(2, _translate("MainWindow", "03"))
        self.mod_no_cb.setItemText(3, _translate("MainWindow", "04"))
        self.mod_no_cb.setItemText(4, _translate("MainWindow", "05"))
        self.mod_no_cb.setItemText(5, _translate("MainWindow", "06"))
        self.mod_no_cb.setItemText(6, _translate("MainWindow", "All"))
        self.mod_no_l.setText(_translate("MainWindow", "Module no :"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_cust()
    ui.setupUi_cust(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
